version: '3'

services: 
  poliweb:
    build: .
    ports: 
      - "3000:3000"
    volumes: 
      - .:/usr/src/app
    environment:
      POSTGRES_DB: development_poliglota
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123123
    depends_on:
      - polidatabase
  

  polidatabase:
    image: postgres
    environment:
      POSTGRES_DB: development_poliglota
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: pass123123
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data:
    
    