default: &default
  adapter: postgresql 
  encoding: unicode 
  host: polidatabase
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  pool: 5
  variables:
    statement_timeout: 5000

test:
  <<: *default
  database: poliglota_test

development:
  <<: *default
  database: <%= ENV["POSTGRES_DB"] %>

production:
  <<: *default
  username: poliglota
  password: poliglota.1234
  database: poliglota
